openapi: 3.0.3
info:
  title: API do Sistema Para Controle de Lojas/Comércios de Pequeno Porte.
  description: |-
    API para lojas/comércios de pequeno porte. Ela faz o controle de produtos, vendedores, clientes, usuários, compras e vendas. Além disso, fornece informações para gestão da empresa.
    
    Esta API foi criada via Swagger com base na especificação OpenAPI 3.0. 

    Links úteis:
    - [Repositório do projeto](https://github.com/adjamirgalvao/pucminas)
    - [Definição da API para a Loja On-line](https://github.com/adjamirgalvao/pucminas/blob/master/projeto/documentacao/api.yaml)
    
    Observações:
    - As rotinas que retornam pdf ou excel, apresentam um problema na visualização da resposta. Existe uma [issue](https://github.com/swagger-api/swagger-ui/issues/5500) no Swagger cadastrada para isso 
  contact:
    name: desenvolvedor
    email: adjamir@gmail.com
  version: 1.0.0
servers:
  - url: https://adjamir2318.c41.integrator.host/mock/api
    description: Mock da API
tags:
  - name: Fornecedor
    description: API relativa a funcionalidade de fornecedores
  - name: Cliente
    description: API relativa a funcionalidade de clientes    
paths:
  /fornecedores:
    get:
      tags:
        - Fornecedor
      summary: Retorna a lista de todos os fornecedores
      description: Retorna a lista de todos os fornecedores
      operationId: gettAllFornecedores
      security:
        - loja_auth:
            - write:fornecedor
            - read:fornecedor  
    post:
      tags:
        - Fornecedor
      summary: Adiciona um novo fornecedor
      description: Adiciona um novo fornecedor
      operationId: addFornecedor
      security:
        - loja_auth:
            - write:fornecedor
            - read:fornecedor
  /fornecedores/{id}:            
    put:
      tags:
        - Fornecedor
      summary: Atualiza um fornecedor
      description: Atualiza o fornecedor informado pelo id
      operationId: updateFornecedor
      security:
        - loja_auth:
            - write:fornecedores
            - read:fornecedores
    delete:
      tags:
        - Fornecedor
      summary: Exclui um fornecedor
      description: Exclui um fornecedor pelo id
      operationId: deleteFornecedor
      security:
        - loja_auth:
            - write:fornecedores
            - read:fornecedores   
  /fornecedores/relatorios/listagem:
    get:
      tags:
        - Fornecedor
      summary: Recupera PDF com a lista de fornecedores
      description: Recupera PDF com a lista de fornecedores
      operationId: getRelatorioListagemFornecedores
      security:
        - loja_auth:
            - write:fornecedor
            - read:fornecedor  
  /fornecedores/exportar/listagem:
    get:
      tags:
        - Fornecedor
      summary: Recupera planilha Excel com a lista de fornecedores
      description: Recupera planilha Excel com a lista de fornecedores
      operationId: getExportarListagemFornecedores
      security:
        - loja_auth:
            - write:fornecedor
            - read:fornecedor  
  /clientes:
    get:
      tags:
        - Cliente
      summary: Retorna a lista de todos os clientes
      description: Retorna a lista de todos os clientes
      operationId: gettAllClientes
      security:
        - loja_auth:
            - write:cliente
            - read:cliente  
    post:
      tags:
        - Cliente
      summary: Adiciona um novo cliente
      description: Adiciona um novo cliente
      operationId: addCliente
      security:
        - loja_auth:
            - write:cliente
            - read:cliente
  /clientes/{id}:            
    put:
      tags:
        - Cliente
      summary: Atualiza um cliente
      description: Atualiza o cliente informado pelo id
      operationId: updateCliente
      security:
        - loja_auth:
            - write:clientes
            - read:clientes
    delete:
      tags:
        - Cliente
      summary: Exclui um cliente
      description: Exclui um cliente pelo id
      operationId: deleteCliente
      security:
        - loja_auth:
            - write:clientes
            - read:clientes   
  /clientes/relatorios/listagem:
    get:
      tags:
        - Cliente
      summary: Recupera PDF com a lista de clientes
      description: Recupera PDF com a lista de clientes
      operationId: getRelatorioListagemClientes
      security:
        - loja_auth:
            - write:cliente
            - read:cliente  
  /clientes/exportar/listagem:
    get:
      tags:
        - Cliente
      summary: Recupera planilha Excel com a lista de clientes
      description: Recupera planilha Excel com a lista de clientes
      operationId: getExportarListagemClientes
      security:
        - loja_auth:
            - write:cliente
            - read:cliente              
  /vendedores:
    get:
      tags:
        - Vendedor
      summary: Retorna a lista de todos os vendedores
      description: Retorna a lista de todos os vendedores
      operationId: gettAllVendedores
      security:
        - loja_auth:
            - write:vendedor
            - read:vendedor  
    post:
      tags:
        - Vendedor
      summary: Adiciona um novo vendedor
      description: Adiciona um novo vendedor
      operationId: addVendedor
      security:
        - loja_auth:
            - write:vendedor
            - read:vendedor
  /vendedores/{id}:            
    put:
      tags:
        - Vendedor
      summary: Atualiza um vendedor
      description: Atualiza o vendedor informado pelo id
      operationId: updateVendedor
      security:
        - loja_auth:
            - write:vendedores
            - read:vendedores
    delete:
      tags:
        - Vendedor
      summary: Exclui um vendedor
      description: Exclui um vendedor pelo id
      operationId: deleteVendedor
      security:
        - loja_auth:
            - write:vendedores
            - read:vendedores   
  /vendedores/relatorios/listagem:
    get:
      tags:
        - Vendedor
      summary: Recupera PDF com a lista de vendedores
      description: Recupera PDF com a lista de vendedores
      operationId: getRelatorioListagemVendedores
      security:
        - loja_auth:
            - write:vendedor
            - read:vendedor  
  /vendedores/exportar/listagem:
    get:
      tags:
        - Vendedor
      summary: Recupera planilha Excel com a lista de vendedores
      description: Recupera planilha Excel com a lista de vendedores
      operationId: getExportarListagemVendedores
      security:
        - loja_auth:
            - write:vendedor
            - read:vendedor              
components:
  securitySchemes:
    loja_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:fornecedores: modify fornecedores in your account
            read:fornecedores: read your fornecedores
    api_key:
      type: http
      scheme: bearer    