openapi: 3.0.3
info:
  title: API do Sistema Para Controle de Lojas/Comércios de Pequeno Porte.
  description: |-
    API para lojas/comércios de pequeno porte. Ela faz o controle de produtos, vendedores, clientes, usuários, compras e vendas. Além disso, fornece informações para gestão da empresa.
    
    Esta API foi criada via Swagger com base na especificação OpenAPI 3.0. 

    Links úteis:
    - [Repositório do projeto](https://github.com/adjamirgalvao/pucminas)
    - [Definição da API para a Loja On-line](https://github.com/adjamirgalvao/pucminas/blob/master/projeto/documentacao/api.yaml)
    
    Observações:
    - As rotinas que retornam pdf ou excel apresentam um problema na visualização da resposta pelo Swagger. Existe uma [issue](https://github.com/swagger-api/swagger-ui/issues/5500) no Swagger cadastrada para este problema. 
  contact:
    name: desenvolvedor
    email: adjamir@gmail.com
  version: 1.0.0
servers:
  - url: https://adjamir2318.c41.integrator.host/mock/api
    description: Mock da API
tags:
  - name: Usuários
    description: API relativa a funcionalidade de usuários  
  - name: Fornecedores
    description: API relativa a funcionalidade de fornecedores
  - name: Produtos
    description: API relativa a funcionalidade de produtos
  - name: Vendedores
    description: API relativa a funcionalidade de vendedores     
  - name: Clientes
    description: API relativa a funcionalidade de clientes  
  - name: Compras
    description: API relativa a funcionalidade de compras  
paths:
  /usuarios/{id}:            
    get:
      tags:
        - Usuários
      summary: Consulta um usuário pelo id
      operationId: getUsuario
      security:
        - api_key:
            - write:usuarios
            - read:usuarios               
    put:
      tags:
        - Usuários
      summary: Atualiza o usuário informado pelo id
      operationId: updateUsuario
      security:
        - api_key:
            - write:usuarios
            - read:usuarios
    delete:
      tags:
        - Usuários
      summary: Exclui um usuário pelo id
      operationId: deleteUsuario
      security:
        - api_key:
            - write:usuarios
            - read:usuarios    
  /fornecedores:
    get:
      tags:
        - Fornecedores
      summary: Retorna a lista de todos os fornecedores
      operationId: gettAllFornecedores
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor  
    post:
      tags:
        - Fornecedores
      summary: Adiciona um novo fornecedor
      operationId: addFornecedor
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor
  /fornecedores/{id}: 
    get:
      tags:
        - Fornecedores
      summary: Consulta um fornecedor pelo id
      operationId: getFornecedor

      security:
        - api_key:
            - write:fornecedores
            - read:fornecedores     
    put:
      tags:
        - Fornecedores
      summary: Atualiza o fornecedor informado pelo id
      operationId: updateFornecedor
      security:
        - api_key:
            - write:fornecedores
            - read:fornecedores
    delete:
      tags:
        - Fornecedores
      summary: Exclui um fornecedor pelo id
      operationId: deleteFornecedor
      security:
        - api_key:
            - write:fornecedores
            - read:fornecedores   
  /fornecedores/relatorios/listagem:
    get:
      tags:
        - Fornecedores
      summary: Recupera PDF com a lista de fornecedores
      operationId: getRelatorioListagemFornecedores
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor  
  /fornecedores/exportar/listagem:
    get:
      tags:
        - Fornecedores
      summary: Recupera planilha Excel com a lista de fornecedores
      operationId: getExportarListagemFornecedores
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor  
  /produtos:
    get:
      tags:
        - Produtos
      summary: Retorna a lista de todos os produtos
      operationId: gettAllProdutos
      security:
        - api_key:
            - write:produto
            - read:produto  
    post:
      tags:
        - Produtos
      summary: Adiciona um novo produto
      operationId: addProduto
      security:
        - api_key:
            - write:produto
            - read:produto
  /produtos/{id}: 
    get:
      tags:
        - Produtos
      summary: Consulta um produto pelo id
      operationId: getProduto
      security:
        - api_key:
            - write:produtos
            - read:produtos     
    put:
      tags:
        - Produtos
      summary: Atualiza o produto informado pelo id
      operationId: updateProduto
      security:
        - api_key:
            - write:produtos
            - read:produtos
    delete:
      tags:
        - Produtos
      summary: Exclui um produto pelo id
      operationId: deleteProduto
      security:
        - api_key:
            - write:produtos
            - read:produtos   
  /produtos/{id}/listarItensCompras: 
    get:
      tags:
        - Produtos
      summary: Consulta os itens de compra que contem o produto
      operationId: getItensComprasProduto
      security:
        - api_key:
            - write:produtos
            - read:produtos                
  /produtos/relatorios/listagem:
    get:
      tags:
        - Produtos
      summary: Recupera PDF com a lista de produtos
      operationId: getRelatorioListagemProdutos
      security:
        - api_key:
            - write:produto
            - read:produto  
  /produtos/exportar/listagem:
    get:
      tags:
        - Produtos
      summary: Recupera planilha Excel com a lista de produtos
      operationId: getExportarListagemProdutos
      security:
        - api_key:
            - write:produto
            - read:produto              
  /vendedores:
    get:
      tags:
        - Vendedores
      summary: Retorna a lista de todos os vendedores
      operationId: gettAllVendedores
      security:
        - api_key:
            - write:vendedor
            - read:vendedor  
    post:
      tags:
        - Vendedores
      summary: Adiciona um novo vendedor
      operationId: addVendedor
      security:
        - api_key:
            - write:vendedor
            - read:vendedor
  /vendedores/{id}:            
    get:
      tags:
        - Vendedores
      summary: Consulta um vendedor pelo id
      operationId: getVendedor
      security:
        - api_key:
            - write:vendedores
            - read:vendedores   
    put:
      tags:
        - Vendedores
      summary: Atualiza o vendedor informado pelo id
      operationId: updateVendedor
      security:
        - api_key:
            - write:vendedores
            - read:vendedores
    delete:
      tags:
        - Vendedores
      summary: Exclui um vendedor pelo id
      operationId: deleteVendedor
      security:
        - api_key:
            - write:vendedores
            - read:vendedores   
  /vendedores/relatorios/listagem:
    get:
      tags:
        - Vendedores
      summary: Recupera PDF com a lista de vendedores
      operationId: getRelatorioListagemVendedores
      security:
        - api_key:
            - write:vendedor
            - read:vendedor  
  /vendedores/exportar/listagem:
    get:
      tags:
        - Vendedores
      summary: Recupera planilha Excel com a lista de vendedores
      operationId: getExportarListagemVendedores
      security:
        - api_key:
            - write:vendedor
            - read:vendedor   
  /usuarios:
    get:
      tags:
        - Usuários
      summary: Retorna a lista de todos os usuários
      operationId: gettAllUsuarios
      security:
        - api_key:
            - write:usuario
            - read:usuario  
    post:
      tags:
        - Usuários
      summary: Adiciona um novo usuário
      operationId: addUsuario
      security:
        - api_key:
            - write:usuario
            - read:usuario
  /clientes:
    get:
      tags:
        - Clientes
      summary: Retorna a lista de todos os clientes
      operationId: gettAllClientes
      security:
        - api_key:
            - write:cliente
            - read:cliente  
    post:
      tags:
        - Clientes
      summary: Adiciona um novo cliente
      operationId: addCliente
      security:
        - api_key:
            - write:cliente
            - read:cliente
  /clientes/{id}:  
    get:
      tags:
        - Clientes
      summary: Consulta um cliente pelo id
      operationId: getCliente
      security:
        - api_key:
            - write:clientes
            - read:clientes   
    put:
      tags:
        - Clientes
      summary: Atualiza o cliente informado pelo id
      operationId: updateCliente
      security:
        - api_key:
            - write:clientes
            - read:clientes
    delete:
      tags:
        - Clientes
      summary: Exclui um cliente pelo id
      operationId: deleteCliente
      security:
        - api_key:
            - write:clientes
            - read:clientes   
  /clientes/relatorios/listagem:
    get:
      tags:
        - Clientes
      summary: Recupera PDF com a lista de clientes
      operationId: getRelatorioListagemClientes
      security:
        - api_key:
            - write:cliente
            - read:cliente  
  /clientes/exportar/listagem:
    get:
      tags:
        - Clientes
      summary: Recupera planilha Excel com a lista de clientes
      operationId: getExportarListagemClientes
      security:
        - api_key:
            - write:cliente
            - read:cliente  
  /compras:
    get:
      tags:
        - Compras
      summary: Retorna a lista de todas as compras
      operationId: gettAllCompras
      security:
        - api_key:
            - write:compra
            - read:compra  
    post:
      tags:
        - Compras
      summary: Adiciona uma nova compra
      operationId: addCompra
      security:
        - api_key:
            - write:compra
            - read:compra
  /compras/{id}:  
    get:
      tags:
        - Compras
      summary: Consulta uma compra pelo id
      operationId: getCompra
      security:
        - api_key:
            - write:compras
            - read:compras   
    delete:
      tags:
        - Compras
      summary: Exclui uma compra pelo id
      operationId: deleteCompra
      security:
        - api_key:
            - write:compras
            - read:compras   
  /compras/relatorios/listagem:
    get:
      tags:
        - Compras
      summary: Recupera PDF com a lista de compras
      operationId: getRelatorioListagemCompras
      security:
        - api_key:
            - write:compra
            - read:compra  
  /compras/exportar/listagem:
    get:
      tags:
        - Compras
      summary: Recupera planilha Excel com a lista de compras
      operationId: getExportarListagemCompras
      security:
        - api_key:
            - write:compra
            - read:compra                  
components:
  securitySchemes:
    api_key:
      type: http
      scheme: bearer    