openapi: 3.0.3
info:
  title: API do Sistema Para Controle de Lojas/Comércios de Pequeno Porte.
  description: |-
    API para lojas/comércios de pequeno porte. Ela faz o controle de produtos, vendedores, clientes, usuários, compras e vendas. Além disso, fornece informações para gestão da empresa.
    
    Esta API foi criada via Swagger com base na especificação OpenAPI 3.0. 

    Links úteis:
    - [Repositório do projeto](https://github.com/adjamirgalvao/pucminas)
    - [Definição da API para a Loja On-line](https://github.com/adjamirgalvao/pucminas/blob/master/projeto/documentacao/api.yaml)
  contact:
    name: desenvolvedor
    email: adjamir@gmail.com
  version: 1.0.0
externalDocs:
  description: Saiba mais sobre o projeto.
  url: https://github.com/adjamirgalvao/pucminas/tree/master/projeto/documentacao
servers:
  - url: https://adjamir2318.c41.integrator.host/mock/api
tags:
  - name: Fornecedor
    description: API relativa a funcionalidade de fornecedores
paths:
  /fornecedores:
    get:
      tags:
        - Fornecedor
      summary: Recupera a lista de fornecedores
      description: Recupera a lista de fornecedores
      operationId: gettAllFornecedores
      responses:
        '200':
          description: Consulta com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fornecedor'         
        '403':
          description: Acesso negado
      security:
        - loja_auth:
            - write:fornecedor
            - read:fornecedor  
    post:
      tags:
        - Fornecedor
      summary: Adiciona um novo fornecedor
      description: Adiciona um novo fornecedor
      operationId: addFornecedor
      requestBody:
        description: Cria um novo fornecedor
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fornecedor'
        required: true
      responses:
        '200':
          description: Atualização com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'          
        '405':
          description: Invalid input
      security:
        - loja_auth:
            - write:fornecedor
            - read:fornecedor
  /fornecedores/{id}:            
    put:
      tags:
        - Fornecedor
      summary: Atualiza um fornecedor
      description: Atualiza o fornecedor informado pelo id
      operationId: updateFornecedor
      parameters:
        - name: id
          in: path
          description: Id do fornecedor para atualizar
          required: true
          schema:
            type: string
      requestBody:
        description: Atualiza o fornecedor informado pelo id
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fornecedor'
      responses:
        '200':
          description: Operacação com sucesso
        '500':
          description: Foi fornecido um ID inválido
        '404':
          description: Fornecedor não encontrado
        '401':
          description: Usuário não está logado
        '403':
          description: Acesso negado ao usuário
      security:
        - loja_auth:
            - write:fornecedores
            - read:fornecedores
    delete:
      tags:
        - Fornecedor
      summary: Exclui um fornecedor
      description: Exclui um fornecedor pelo id
      operationId: deleteFornecedor
      parameters:
        - name: id
          in: path
          description: Id do fornecedor para excluir
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operacação com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'           
        '500':
          description: Foi fornecido um ID inválido
        '404':
          description: Fornecedor não encontrado
        '401':
          description: Usuário não está logado
        '403':
          description: Acesso negado ao usuário
      security:
        - loja_auth:
            - write:fornecedores
            - read:fornecedores   
  /fornecedores/relatorios/listagem:
    get:
      tags:
        - Fornecedor
      summary: Recupera PDF com a lista de fornecedores
      description: Recupera PDF com a lista de fornecedores
      operationId: getRelatorioListagemFornecedores
      responses:
        '200':
          description: Consulta com sucesso
          content:
            application/pdf:
      
        '403':
          description: Acesso negado
      security:
        - loja_auth:
            - write:fornecedor
            - read:fornecedor  
            
components:
  schemas:
    Fornecedor:
      required:
        - _id
        - nome
        - tipo
        - identificacao
        - endereco
      type: object
      properties:
        _id:
          type: string
          description: Id do fornecedor
          example: "63cf180478fa75fe3c95ed48"
          readOnly: true
        nome:
          type: string
          description: Nome do fornecedor
          example: "Lojão do Condomínio"
        tipo:
          type: string
          description: Tipo do fornecedor
          enum:
            - pf
            - pj
          example: "pf"
        identificacao:
          type: string
          description: CPF/CNPJ do Fornecedor
          example: "39629415500" 
        endereco:
          type: object
          properties:
            rua:
              type: string
              example: "Rua dos pedestres"
            numero:
              type: string
              example: "S/N"
            complemento:
              type: string
              example: "Apto 1000"
          required:
            - rua
            - numero          
  requestBodies:
    Fornecedor:
      description: Objeto fornecedor que será adicionado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Fornecedor'
  securitySchemes:
    loja_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:fornecedores: modify fornecedores in your account
            read:fornecedores: read your fornecedores
    api_key:
      type: http
      scheme: bearer    